### ISSUE TITLE
Support for the development of the Cyrillic script in Unageo font family

### ISSUE THREAD

**Issue by StefanPeev** [RichardSepsi/Unageo#4]
@RichardSepsi Congratulations on the successful project and the unusual way of its creation. (There are few who can get from Inkscape and FontForge to a variable font). If you are interested in the development of the project, I could assist you with comments and my suggestions regarding the Cyrillic script.

**Comment by RichardSepsi** [comment]
Hello, Thank you. Feel free to share your ideas and suggestions, they are more than welcome.
