### ISSUE TITLE
Alternative glyph variants for cyrillic

### ISSUE THREAD

**Issue by lexuzieel** [RichardSepsi/Unageo#6]
First of all, thank you for this awesome font — I really enjoy it!

I want to use this font primarily for titles with cyrillic text and I have noticed that three glyphs look a bit out of place.
For lowercase characters **к**, **ю** and **ж** you use variants that are extended upwards similar to how it is for the lowercase latin **k**.

While for english texts it makes perfect sense, it looks out of place when used with cyrillic. My suggestion would be to add alternative glyphs for these characters, this way we can preserve unique style of this font face but give users and ability to adjust it.

Here is the visualization of what I am talking about:

![image](https://github.com/user-attachments/assets/aebe053a-4144-4f31-a7f5-33c4c66b8b9f)

ключ жираф — this is how this text looks in the majority of cyrillic fonts and people are used to this.

In most of the fonts these characters look different for cyrillic, especially with k: к / k

Would you be open to a PR if I made the adjustments? Though I've never used fontforge, but I've already installed it and fiddled a bit with your font.

**Comment by kenmcd** [comment]
From the front page of this repo...

> Unageo cyrillic was made in bulgarian style, that uses more rounded shapes and differentiated letter heights which makes it easier to tell letters apart and further improves readability.

**Comment by lexuzieel** [comment]
Oh right, I see, my bad. I thought bulgarian style was regarding letters д, г and л. I've read more upon this and indeed it seems correct. I guess in this case I should just create my own fork then

**Comment by RichardSepsi** [comment]
Thank you for your input. I'm glad you like the font.
Yeah, some lower case characters are extended upwards, because that's a part of the "bulgarian" style. As of now, I don't really know how to make alternative glyphs and unfortunately I currently don't have much time to play with it. However, it's not a bad suggestion and I might add this sometime in the future when I have time. And of course feel free to create a fork anytime if you want to.

**Comment by lexuzieel** [comment]
Interestingly enough there is an OpenType feature specifically for Bulgarian Cyrillic (mentioned here in the PS: https://type.today/en/journal/bulgarian), however they mention it's currently unstable.
I will see how hard it is to implement glyph variants and whether it's feasible for the web (I have no prior experience with font design, so I currently have no idea if it's even doable). Worst case scenario I will just update the glyphs in my fork.
Either way I will keep you posted here if I make any progress.
Cheers!

**Comment by kenmcd** [comment]
Sofia Sans has the default shapes set to Bulgarian - like this font.
That font has a localization for Russian to get the other shapes.
So you could copy what they did.
https://github.com/lettersoup/Sofia-Sans
https://fonts.google.com/specimen/Sofia+Sans

**Comment by RichardSepsi** [comment]
I have found some interesting information about this. It looks like the "cursive style" font of eastern cyrillic looks different from the Bulgarian style with some letters not being extended like you mentioned and some other differences like a different "d". I think it would be a good idea to add alternative forms of the letters that match more with eastern cyrillic. I don't know when I will have time to add it, but there are also other things that I would like to update, so I'll try.

Here is some kind of an article about it.
https://www.myfonts.com/a/font/content/cyrillic-script-variations-and-the-importance-of-localisation

This is the style I think I would follow.
![Screenshot_20241107-080224](https://github.com/user-attachments/assets/0233ca13-4cb9-4ac0-9f75-ed316e551a39)

**Comment by lexuzieel** [comment]
Yup, just dove deep into this font history rabbit hole myself and apparently modern russian cyrillic comes from older bulgarian cursive, hence bulgarian variants are more rounded. From my experience I can say that people mix both of these styles in russian but only for some letters. i.e. those in my original post are not used, whilst "L", "t", "d", "i", "p", "d", "g" are interchangeable and don't come out as "weird" in russian cyrillic.

Because of this I think the best approach would be to change the subset of glyphs and keep an option to use some others interchangeably (no idea how to implement this, but this is an ideal case).

In my opinion, only к, ю, ж, в ("v") and з should be tweaked for russian cyrillic, since bulgarian variants are not used there at all. However, other characters are interchangeable and it is more of a stylistic choice in russian and are still being actively used.

Therefore I think those bulgarian style characters should be kept as it is since that highlights Unageo design choice (like letters "L", "d", "g", "p" which give out a friendlier vibe).

On the image below I've highlighted with red characters I propose to tweak, whilst those underlined with green I think can be kept since they are widely used in russian:

![image](https://github.com/user-attachments/assets/12bd03c5-7717-4201-9484-2dfd05a1cad9)

**Comment by RichardSepsi** [comment]
Yeah, that's how I imagined it. I will add alternative forms for к, ю, ж, в, з and additionally I would also add a separate alternative form for lowercase д that uses the eastern cursive form, just like in the picture I sent in my previous message.

**Comment by RichardSepsi** [comment]
I updated the fonts and now they should have stylistic sets: "ss01" for к, ю, ж, в, з and "ss02" for д. If something isn't working properly or there is something else that you think should be changed, please let me know.

**Comment by lexuzieel** [comment]
Wow, this was really fast! I have just tested it and it looks perfect, thanks a lot!
Looks like it also just works on the web through CSS by using `font-feature-settings`:

```
.font-unageo {
    font-feature-settings: "ss01" on;
}
```

Posting this for future reference if somebody stumbles upon this.

Once again, I truly appreciate the tweaks you have made since I do intend on using this font — thank you!
